### ISSUE TITLE
 AMD Ryzen 5 5700G with Cezanne not working

### ISSUE THREAD

**Issue by efschu** [Ricks-Lab/gpu-utils#133]
debian testing with running kernel:
`5.19.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.6-1`

`AMD Ryzen 5 5700G`

```
09:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [1002:1638] (rev c8)
	Subsystem: ASUSTeK Computer Inc. Cezanne [1043:8809]
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu
```

```
./gpu-mon
┌─────────────┬────────────────────┐
│Card #       │       card0        │
├─────────────┼────────────────────┤
│Model        │      Cezanne       │
│GPU Load %   │        ---         │
│Mem Load %   │        ---         │
│VRAM Usage % │        ---         │
│GTT Usage %  │        ---         │
│Power (W)    │        0.01        │
│Power Cap (W)│        ---         │
│Energy (kWh) │        ---         │
│T (C)        │        41.0        │
│VddGFX (mV)  │        1437        │
│Fan Spd (%)  │        ---         │
│Sclk (MHz)   │        2300        │
│Sclk Pstate  │         1          │
│Mclk (MHz)   │        ---         │
│Mclk Pstate  │        ---         │
│Perf Mode    │        ---         │
└─────────────┴────────────────────┘

./gpu-chk
Using rickslab-gpu-utils  3.7.8 
Using python 3.10.7
           Python version OK. 
Using Linux Kernel: 5.19.0-1-amd64
           OS kernel OK. 
Using system type: systemd
           System type has been Validated. 
Using Linux distribution: Debian GNU/Linux bookworm/sid
           Distro has been Validated. 
amdgpu/rocm version: UNKNOWN
           rickslab-gpu-utils can still be used. 
python3 venv is installed
           python3-venv OK. 
rickslab-gpu-utils-env available
           rickslab-gpu-utils-env OK. 
Not in rickslab-gpu-utils-env, (Only needed if you want to duplicate development env)
           rickslab-gpu-utils-env can be activated per User Guide. 
Checking apt-key keyring:
           rickslab repository is not using apt-key keyring. 

./gpu-ls
Detected GPUs: AMD: 1
AMD: amdgpu/rocm version: UNKNOWN
AMD: Wattman features enabled: 0xfffd7fff
Total of 1 GPU: 1 is rw, 0 are r-only, and 0 are w-only

Traceback (most recent call last):
  File "/home/efeu/Downloads/gpu-utils/./gpu-ls", line 174, in <module>
    main()
  File "/home/efeu/Downloads/gpu-utils/./gpu-ls", line 149, in main
    gpu_list.read_gpu_pstates()
  File "/home/efeu/Downloads/gpu-utils/GPUmodules/GPUmodule.py", line 2502, in read_gpu_pstates
    gpu.read_gpu_pstates()
  File "/home/efeu/Downloads/gpu-utils/GPUmodules/GPUmodule.py", line 1236, in read_gpu_pstates
    lineitems[0] = int(re.sub(':', '', lineitems[0]))
IndexError: list index out of range
```

**Comment by Ricks-Lab** [comment]
I noticed that this error is occurring within a try/except.  It should be handled and result in no valid data read from p-states.

**Comment by efschu** [comment]
Well it's more the gpu-mon is producing not real data?

**Comment by Ricks-Lab** [comment]
There is 2 sources of p-state data:

- P-state table in the `pp_od_clk_voltage` file is a complete table but only available when overclocking is enabled.  Used by `gpu-ls` but not `gpu-mon`
- The `pp_dpm_*clk` files give the current frequency and p-state.  This is used by `gpu-mon`

**Comment by efschu** [comment]
Ehm, soo actual I did not understand the "solution"

What am I supposed to do, to get it work?

**Comment by Ricks-Lab** [comment]
AMD APUs have limited driver support.  I think you are seeing all supported data.  You can use `gpu-ls --raw` to make the utility attempt to read all possible sensors.  

The error message looks to be the result of removing the original try/except.  Let me know if that is not the case.
